// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuAblNwkXk2FeqNHQYIcavBbP6HRH_8mk',
    appId: '1:1052769229623:android:ff91dc0e9294f4ec6d98b2',
    messagingSenderId: '1052769229623',
    projectId: 'huda-app-44bdb',
    databaseURL: 'https://huda-app-44bdb-default-rtdb.firebaseio.com',
    storageBucket: 'huda-app-44bdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJbswEPDo-n-5WtQ6cI0UflIhyUdp1AlI',
    appId: '1:1052769229623:ios:4f033ae9176312c96d98b2',
    messagingSenderId: '1052769229623',
    projectId: 'huda-app-44bdb',
    databaseURL: 'https://huda-app-44bdb-default-rtdb.firebaseio.com',
    storageBucket: 'huda-app-44bdb.appspot.com',
    iosClientId:
        '1052769229623-jeedfn29q0h0524tvf43sdkss6t63jq5.apps.googleusercontent.com',
    iosBundleId: 'com.example.hudaClinicMobile',
  );
}
